language: nix
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "./.odcdb"
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script:
- nix-shell --command "./gradlew check"
- nix-shell --command "timeout 300 ./.travis-cat_owasp_depcheck_reports.sh || true"
- if [[ ( "$TRAVIS_PULL_REQUEST" = "false" ) && (( "$TRAVIS_BRANCH" = "master" ) || ( "$TRAVIS_TAG" != "" )) ]]; then nix-shell --command "./gradlew docker" && export TE_DEPLOY=true; fi
deploy:
  provider: script
  script: nix-shell --command "bash docker_push"
  on:
    condition: "$TE_DEPLOY != ''"
    all_branches: true
env:
  global:
    secure: wv7BDZ/aNEKiXgEE3Lcc326P+7LHB4NiuO/kPdicpuc2M8AlMdSoIedfkuBHTdI6SkjvpjFXaJDzUoDDEdXweMbW9Id+S9CifnQPKNcdB9VcXoCr4dPeIB6QWRGcMvYsuQM7vYY/3WwTF9h4Rj5yJ22cVikndaIwREmhh1Bz6BqweZ+MEPgmpZ4Z0Fut+a8QcgC9SLWMWiIhBtpMcGu7FTeNdKyBrOJPtThfllLLN3a6IQS435Hlm5tNRZE7u+pTfL5Zv/nmvQpuXaKb0IoMuO7IBkxablaD5h7iCO1o0vZjO/HWYY4QWBaz9AY7VFoTqTz32h2R8ZqmzEb3eHVw3tBU5Jc3JntYE8NgE3jdds8LWMxcIN4Ud2/CzOKwGqT2IbBgr1qpkCwqsJD46GZdCJhmxTqD9Rv9lPCEpHiw1MrJ7dYKFlstF9hbhbI5qYCqA9UPTct7FAmYKfYqz1ZNFUKlDFDMZKDoLfN0Ojw6p761u3OTSoh43rlr/+e78QO/mlUJ2k4m+MPtP2kpbpc5GQRSMcPtULEh96tCaTteUVjlpFWDnTVj8hpUcoAQ4LDN7wxQEfCAXlk/e8SXBczcAw+1jOwPfPbIED6Pv+9HlRj1S2ZJEnpRE8uVUouuBj+EWDSomcvHpJ8iGhsf0xim3uCjm6KuLpVInv6p7sBhkf8=
