language: nix
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "./.odcdb"
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script:
- nix-shell --command "./gradlew check"
- nix-shell --command "timeout 300 ./.travis-cat_owasp_depcheck_reports.sh || true"
- nix-shell --command "./gradlew docker"
- if [[ ( "$TRAVIS_PULL_REQUEST" = "false" ) && (( "$TRAVIS_BRANCH" = "master" ) || ( "$TRAVIS_TAG" != "" )) ]]; then export TE_DEPLOY=true; fi
deploy:
  provider: script
  script: nix-shell --command "bash docker_push"
  on:
    condition: "$TE_DEPLOY != ''"
    all_branches: true
env:
  global:
    - # Environment variables for Docker 
    - secure: "W0pZh0w+FdL8I6iWxcZuYbpowtHMjeMyTz5HwwrA2FyglPu3ybI7+0VQ88YTQa9Si0sghKl1hFz49dK+0y7ve9Pcwbfs90R/MlM7x/WYjR90dr4lfvWAGdheWGdhwfM60knVjrGbspJ7YBikfZRzOI8jWvhkjLsWoHR8arSdVp2O3kkpoaqvXL48rraeFrx/zCXqRIYw6dTpdVw+BJHbZZcvExTD/LdgEwVd6ctiRFKsBgfJ4ozgHTJL6xDK8CxwJFeaJZWyDjYE7+hJTPz2l9EATGnxGmnU26SItOzrk5/pKVy9reNL6khXwbvW91VVQj9aaDvMcZrW+sAPqpOF7LLtwy1kycBNV11WC3Xvy+n+KJl2Vy9EAEYDZ5E4QqZEUEPxAfU/dfn4WO17mtfco2WlYRUdovxgA7IOcQFTVUg+kMFnwlZskjgpp4O6oXyLUHHTrAFD+IkD8+7+G9BQxVKVBRWevooIaXGbCXGytVtLZBfTIR5U67OgNmVM7xHj/Hcwt767hBo7PMySnUukIYwMliRWMwBR7oiCqSuO4wTCZf2PQWdaalGTQ2C/O406U5ERXzgiXI4vTo9VkteJj8wixqYr7Oy2xwZuzQLnX61Ol5Z8aLhU+PDiiqRRoccbjr52s3xme4wiG/Qbge27+MjZL72liY+j4Vb0aBroS8s="
    - secure: "aBN3bWs5YcOUc12XpCejIq2Oydmcd1m3tD2YSafhD5BnZdXnR3acdmxS0Pe/SBgzGYcv38gY9o5P8vQat+nIi9j0m4u5pSfy8bRX5yHndaVKJV/tFQrADJ4qyqGNizrJM8d6MUX3gaP8tD8/4qQh8ElErtPe7wCJL6OvJGu+414R/WAgmDuay3+yhMI8rIt7AiKj1j/k1H+yZIoPkjzLgK4IbK7dI0ZR18RX0K+Z0neBZ4mlXkPdVjod6erEdJcD+/cIJKIbVQgs98ryJLIhoaaCA/m9riINkaUODk33Sc2ZDNuIyIttcvAzhpXQx+eWT1Kb8bZBJBKrEY64XKfQoI2rzuj6QomP5Ffzsir8xV4anPMJ80sEwhL9Yh9PxwdCptqvCc+8xHwlPRunBWJl2yb7CpLAI7/hMuhgzCGiBmLFQYiq7LugetVtCXJ96IhUhjwMpX6ZdwgVO+i+wLMm3Er4VV3diCfIB1yzxS6bEJI2vufUdgzXN9xXG27qaYfqAZ5q+AJGMbpGvj59sJSVWNZu5dgWapq2Q1elXpBRGxPpMndHZMxvpoUgrz9eRwhNNlMHIHN4h89NVhdDCf6O1SwmfY5WUIVGizXYFwnCN8Qe1zQN5m5KCG458x3tWvQMDsxp+NSdY7zy8FWQPJ/a0hMg+4ZHRtt+Ghc0si2PgL4="
    