#!/bin/sh
if [[ $TRAVIS_TAG = v* ]]; then
  docker tag testeditor/persistence:SNAPSHOT "testeditor/persistence:$TRAVIS_TAG"
  docker tag testeditor/xtext:SNAPSHOT "testeditor/xtext:$TRAVIS_TAG"
  docker tag testeditor/persistence:SNAPSHOT "testeditor/persistence:latest"
  docker tag testeditor/xtext:SNAPSHOT "testeditor/xtext:latest"
fi
