#!/bin/sh
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push testeditor/persistence:SNAPSHOT
docker push testeditor/xtext:SNAPSHOT
if [[ $TRAVIS_TAG = v* ]]; then
  docker push testeditor/persistence:SNAPSHOT "testeditor/persistence:$TRAVIS_TAG"
  docker push testeditor/xtext:SNAPSHOT "testeditor/xtext:$TRAVIS_TAG"
  docker push testeditor/persistence:SNAPSHOT "testeditor/persistence:latest"
  docker push testeditor/xtext:SNAPSHOT "testeditor/xtext:latest"
fi
