/*
 * generated by Xtext 2.11.0
 */
package org.testeditor.web.backend

import org.eclipse.xtext.web.server.persistence.IServerResourceHandler
import org.testeditor.tsl.dsl.web.TslWebModule

/**
 * Use this class to register additional components to be used within the web application.
 */
class TslEditorWebModule extends TslWebModule {

	def Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
		return FileResourceHandler
	}

}
