remoteRepoUrl: git@github.com:test-editor/test-editor-examples.git
applicationId: org.testeditor.web.backend.persistence
server:
  applicationConnectors:
  - type: http 
    port: 9080
  adminConnectors:
  - type: http
    port: 9081
