remoteRepoUrl: %TARGET_REPO%
branchName: %BRANCH_NAME%
privateKeyLocation: %KEY_LOCATION%
knownHostsLocation: %KNOWN_HOSTS%
repoConnectionMode: %REPO_MODE%
server:
  applicationConnectors:
  - type: http 
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
